#!/bin/bash
GITHUB_USERNAME= "Najam-Waseem"
GITHUB_TOKEN= "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"

mkdir task_1
cd task_1
touch practice.py
echo " Hi this is task 1">touch.py
cd -
git add .
git commit -m "task 1 practice"

git push https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${USERNAME}/-W_Assignments.git master

