#!/bin/bash
USERNAME= "Najam-Waseem"
TOKEN= "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"

mkdir task_1
cd task_1
touch practice.py
echo " Hi this is task 1">touch.py
cd -
git add .
git commit -m "task 1 practice"

git push https://${USERNAME}:${TOKEN}@github.com/{USERNAME}/-W_Assignments.git origin main

